server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
  
  redis:
    hostName: 127.0.0.1
    port: 6379
    password: 
    maxActive: 8
    maxWait: -1
    maxIdle: 0
    timeout: 0